name: Windows Build

on: [ push ]

jobs:
  build:
    runs-on: "windows-latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Rust Build
        run: |
          cargo build --release

      - name: Prepare Dist
        run: |
          mkdir dist
          cp "./target/release/minmodmon-server.exe" "./dist/minmodmon-server.exe"
          cp "./Config.toml" "./dist/Config.toml"

      - uses: actions/upload-artifact@v4
        with:
          name: minmodmon
          path: ./dist
